flags:
  highlighting-kate: { pcre-light: true }
packages:
  - '.'
  - location: '../indieweb-algorithms'
    extra-dep: true
  - location: '../hs-duktape'
    extra-dep: true
  - location: '../pcre-heavy'
    extra-dep: true
  - location: '../microformats2-parser'
    extra-dep: true
  - location: '../gitson'
    extra-dep: true
  - location:
      git: https://bitbucket.org/myfreeweb/haskell-jwt.git
      commit: 40387dd17c1b8fb116d27c0a0b65f76b6d4203ce
    extra-dep: true
  - location:
      git: https://github.com/myfreeweb/wai.git
      commit: a2327adcd68ff58b32c5d0be4d3cebfc21765b6d
    extra-dep: true
    subdirs:
      - wai-app-static
  - location:
      git: https://github.com/myfreeweb/wai-middleware-static.git
      commit: b01d98e47fdfd0b5c28cb6789efe280aeb76a231
    extra-dep: true
  - location:
      git: https://github.com/chrisdone/shell-conduit.git
      commit: 81088e2af9c72cf2806b3e8e9825282774a76e73
    extra-dep: true
extra-deps:
  - lens-datetime-0.2.1
  - setters-0.1
  - git-embed-0.1.0
  - highlighting-kate-0.6.1
resolver: lts-5.6
